spring.jpa.hibernate.ddl-auto: none
spring.datasource.url: jdbc:hsqldb:file:addon-db # Use a file-based backing store for HSQL
dbms:
  security:
    auth_enabled=false:
addon:
  key: neo4j
  base-url: https://8dee-84-252-147-229.ngrok.io

logging.level.com.atlassian.connect.spring: DEBUG
